---
title: "Annotated Bibliography"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document contains short summaries of relevant papers. The intention is this document will inform our background section. 

# Miscellaneous thoughts

Most of these papers only seem to be describing either Dec results or Hep results, not both. 

Most of these papers are using data from IAAF. Why? 

A lot of papers only analyse top scores/performers. 

We're going to have a massive sample size. Consider commenting on the cluster analysis and 3- or 5- cluster solution for the decs. (woolf et al., 2007; cox & dunn, 2002)

It may be that the dec scoring system naturally encourages the sprinters, who can swallow mediocre scores in SP DT and JT events. Because of the different number of events, the Hep might not disadvantage certain profiles as much ... we should consider this. The idea of our profiles are that these are perhaps distinct combinations of physiologies and talents in multi-events, but when combined with the constraints of the scoring system, optimization looks different for each event. We should consider combining hep and dec data ... what would that look like?

Most cluster analyses have used scores, but each score calculation is a nonlinear transformation of the event results, thus there is a difference in the change in standardized scores for the same change in standardized performance across events. This will impact the analyses. While perhaps not an issue when making interpretations about the relationship of performances with an eye to maximize total score, there is a clear implication when making interpretations on the physiological taxation of the events and implications for training regimens. 

Van Damme et al. and others have done correlation analyses, and found that in a restricted sample of excellent performances there are some negative pairwise correlations, implying there are specialists. However, in a larger database, there are mostly all positive correlations: 

- maybe we should do this study in two parts. One part using top athletes, and doing an LPA, and a growth model for them since they are known. And another with the NCAA data, and compare the two, to discuss implications for training and development. 
- perhaps we also search IAAF for the athletes in our NCAA dataset to get more longitudinal data. 

# Decathlon

## Cox and Dunn (2002)

Title: [An analysis of decathlon data](https://rss.onlinelibrary.wiley.com/doi/pdf/10.1111/1467-9884.00310?casa_token=qo3zCjfIAuQAAAAA:j1kg5-BC_9cRxowJRmlGJ4M7jdcnpkcSHn10b0MvyaZdrmHPuGVCqMxxL6Xufii_opbYOhrS9Z2yKQ)
<br>
Citation: Cox, T. F., and Dunn, R. T. (2002). An analysis of decathlon data. Journal of the Royal Statistical Society: Series D (The Statistician), 51(2), 179-187.
<br>
<br>
Data: IAAF World Championships between 1991-1999 (5 meets)
<br>
RQ: Internal Structure, and, Is event order fair?
<br>
<br>
Methods: Hierarchical Cluster Analysis, correlational analysis
<br>
Findings: 

- Clusters: Three cluster solution: {100m, 400m, LJ, 100mh}, {SP, DT, JT, PV}, {HJ, 1500m}. Two cluster solution separates 'track' events from 'field' events ({100, 400, 110, LJ}, {SP, DT, JT, PV, HJ, 1500}) and accounts for 50% of the variance

- Variances: "The order of the 10 sample standard deviations is: 400m, 100m, 110mh, Dis, SP, LJ, HJ, Jav, PV, 1500m. Note that the three smallest standard deviations are for track events. The field events have larger standard deviations. This suggests that the decathlon could favour those athletes who are good in the field events." (p. 183)

- Fairness: "for four [out of 5] of the meetings, the events ‘agree’ with each other on the ranking of the athletes." (p. 184) "tentative conclusion from the above analyses is that the decathlon favours those athletes who can do well at the field events." (p. 187)


## Heazlewood et al. (2014)

Title: [The factor structure of the decathlon and heptathlon: Implications for training strength, power, speed, and endurance](https://researchers.cdu.edu.au/en/publications/the-factor-structure-of-the-decathlon-and-heptathlon-implications)
<br>
Citation: Heazlewood, T., Gahreman, D., & Lee, J. (2014). The Factor Structure of The Decathlon and Heptathlon: Implications for Training Strength, Power, Speed and Endurance. Journal of Australian Strength and Conditioning, 22(5), 161-166. https://www.strengthandconditioning.org/jasc-22-5
<br>
<br>
Data: IAAF World Championships between 1991-1999 (5 meets)
<br>
RQ: Internal Structure, and, Is event order fair?
<br>
<br>
Methods: Hierarchical Cluster Analysis, correlational analysis
<br>
Findings:

## Majchrzak et al. (2010)

Title: Developmental Tendencies of Results in Female Heptathlon in the Olympic Games during the Years 1984-2008
<br>
Citation: Majchrzak, K., Kamrowska-Nowak, M., & Byzdra, K. (2010). Developmental tendencies of results in female heptathlon in the Olympic Games during the years 1984-2008. Baltic Journal of Health and Physical Activity, 2(2), 158-163.
<br>
<br>
Data: Olympic games between 1984 - 2008 (7 meets), Top 20 female athletes. 
<br>
RQ: 
<br>
<br>
Methods: Correlational analysis
<br>
Findings: 

- Correlation between event score and total score show many changes over the two decades (see Table 5)
- In the last twenty years, top heptathletes have improved the most in the throwing events, on aggregate.
- "A correlation analysis showed that 100mh, 200m, and LJ had the biggest influence on the final result in heptathlon" (p. 162)

## Woolf et al. (2007)

Title: Grouping of decathlon disciplines
<br>
Citation: Woolf, A., Ansley, L., & Bidgood, P. (2007). Grouping of decathlon disciplines. Journal of Quantitative Analysis in sports, 3(4).
<br>
<br>
Data: personal best decathlon results over 8000pts in international competitions between 1986 and 2005
<br>
RQ: 
<br>
<br>
Methods: Cluster analysis
<br>
Findings: 

- Three cluster solution: {100m, 400m, 110mh, LJ, PV, HJ}, {SP, DT, JT}, {1500m}
- Four cluster solution: {100m, 400m, 110mh, LJ, PV}, {SP, DT, JT}, {HJ}, {1500m}
- Five cluster solution: {100m, 400m, 110mh, LJ}, {SP, DT, JT}, {PV}, {HJ}, {1500m}
- The five cluster solution is better than the three cluster solution, even in a re-analysis of Cox and Dunn (2002)'s data.
- "All six solutions assigned the first three track 'running' disciplines to a different group from the three 'throwing' disciplines (p. 5)
- Small sample size may not have power to demonstrate the superiority of the 5-cluster solution. This study has larger sample size than Cox and Dunn (2002), and while results are similar, it appears that 5-cluster solution is better. 
- "the composition of the clusters suggests that athletes who perform better in the sprint/track disciplines may be afforded an advantage as there are four disciplines in which they are likely to do well; whereas only three of the field disciplines are contained in the next largest cluster. This assumption is further strengthened by the observation that the average ranking of the top ten decathletes in the disciplines that comprise the first cluster is 11th, while their average ranking in the disciplines that comprise the second cluster is 27th."  *Well, perhaps the 'sprinter' profile is an easier path, but are they really better within the profile?*


## Bilic (2015)

Title: Determination of taxonomic type structures of top decathlon athletes
<br>
Citation: Bilić, M. (2015). Determination of taxonomic type structures of top decathlon athletes. Acta Kinesiologica, 9(1), 20-23.
<br>
<br>
Data: Top 100 performances all time? Compared to a Senior list of 350 performances? (*this paper is hard to read, its translation into english is poor*)
<br>
RQ: Are there profiles? 
<br>
<br>
Methods: Canonical discriminative analysis, hierarchical cluster analysis
<br>
Findings: 

- Three profiles. Top one is a dominating sprint-jump qualities. Throwers and endurance profile is the worst. 
- This paper has some stuff about aerobic-anaerobic systems that I can't quite make out both due to content knowledge and the poor quality of translation ...
- Successful athletes in terms of their aptitude and motor skills

## Brodani et al. (2020)

Title: Classification of athletic decathlon using methods of hierarchical analysis
<br>
Citation: BROĎÁNI, J., DVOŘÁČKOVÁ, N., & CZAKOVÁ, M. (2020). Classification of athletic decathlon using methods of hierarchical analysis. Journal of Physical Education & Sport, 20 (S6), 3253-3259.
<br>
<br>
Data: Scores about 8000 from IAAF competitions between 1986-2019 (n=255)
<br>
RQ: Identify groups of athletic disciplines affecting sport performance in decathlon
<br>
<br>
Methods: hierarchical clustering
<br>
Findings: 

- four groups of disciplines: {100m, 400m, LJ, 110mh, PV}, {HJ}, {1500}, {SP, DT, JT}
- stability test - 85.71%
- similar to Woolf et al. 2007 and Cox and Dunn 2002. 

## Brodani et al. (2020)

Title: Share of athletic disciplines on average performance in decathlon of men with a value of 8282.74 points
<br>
Citation: Broďáni, J., Czaková, M., Kováčová, N. (2020). Share of athletic disciplines on average performance in decathlon of men with a value of 8282.74 points. Physical education, sport and olympics, Proceedings report of international scientific conference. Ružomberok : VERBUM vydavateľstvo KU, 2020. [In press]. 

<br>
<br>
Data: 255 decathlon scores from IAAF above 8000 points (as of Dec 2019)
<br>
RQ: versatility?
<br>
<br>
Methods: simple linear regression predicting total score from day 1, and then day 1 and day 2 events. 
<br>
Findings: 

- a slr model based on day 1 events has an rsquared of .5495

## Kostial (1993)

Title: A Structure of Performance in decathlon
<br>
Citation: Koštiaľ, J. (1993). A Structure of Performance in decathlon. Physical Education and Sport, 3(4): 19-22. 
<br>
Koštiaľ, J. (1993). Štruktúra športového výkonu v desaťboji. Tel. Vych. Sport,(4), 19-22. 
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: 
<br>
Findings: 

- two disciplines from the first day contributed to their final performance (in top decathletes)
- **I can't actually find this paper.**

## Brodani (2006)

Title: Decathlon with an Average Performance of 7219.91 Points
<br>
Citation: Broďáni, J. (2006). Decathlon with an Average Performance of 7219.91 Points. Journal Of Coimbra Network On Excercise Sciences. 3(1): 63-66. 

<br>
<br>
Data: 33 performances, with an average score of 7219
<br>
RQ: 
<br>
<br>
Methods: simple linear regression
<br>
Findings: 

- lower score decathlon refers to low versatility and preference of running and jumping over technical throwing disciplines. 
- this is basically the same as Brodani et al. (2020), only with different data, and a different conclusion, only the model looks the same, and has similar results. 
- also, scores are for sure collinear -- this isn't addressed. 

## Pavlovic and Idrizovic (2017)

Title: Factor analysis of world record holders in athletic decathlon
<br>
Citation: Pavlović, R.,Idrizović, K.(2017). Factor analysis of world record holders in athletic decathlon. Sport Science, 10(1): 109-116.
<br>
<br>
Data: Top ten decathlon scores of all time, between 1984-2016
<br>
RQ: 
<br>
<br>
Methods: PCA
<br>
Findings: 

- Typology of top decathletes as jumper-thrower-runner (first component)
- Second component is "runner-sprinter", and third is "jumper-thrower".

## Pavlovic (2017)

Title: Discipline homogeneity based on the most successful decathlon scoring placement
<br>
Citation: Pavlović, R.(2017). Discipline homogeneity based on the most successful decathlon scoring placement. Turk J Kin. 3(1): 6-11. 
<br>
<br>
Data: ten best decathlon performances between 1984-2016
<br>
RQ: 
<br>
<br>
Methods: hierarchical cluster analysis
<br>
Findings: 

- 110m 110mh 400m PV and LJ were clustered, and then SP DT JT and HJ. 
- This is the same data as the other Pavlovic 2017 paper. I'm not sure why they weren't together.

## Park and Zatsiorkij (2011)

Title: Multivariate statistical analysis of decathlon performance results in olympic athletes (1988–2008)
<br>
Citation: Park, J., Zatsiorsky, V. M. (2011). Multivariate statistical analysis of decathlon performance results in olympic athletes (1988–2008). World Acad. Sci. Eng. Technol, 5: 985-988.
<br>
<br>
Data: Olympic decathletes between '88 and '08 (n=166)
<br>
RQ: determine a limited number of latent factors (‘motor abilities’) that define success in decathlon (reproduce Zatsiorsky and Godik 1962)
<br>
<br>
Methods: PCA
<br>
Findings: 

- total score mainly influenced by 100m 400m 110mH and LJ
- first component is "sprinting" (100m, 400m, 11mh, and negative LJ)
- second component is "throwing jumping" (JT, SP, DT HJ, PV)
- third component is 1500m
- "In 1962, V. Zatsiorsky and M. Godik performed factor
analysis (centroid method) of the decathlon performance in
athletes participated in 1960 Olympic Games. The study
was motivated by the desire to determine a limited number of
latent factors (‘motor abilities’) that define success in
decathlon and, as a consequence, to help coaches and athletes
in designing optimal training programs that take into
consideration the inter-event similarity and possible transfer of
training results." (p. 1)
- V.M. Zatsiorsky, and M.A. Godik, “Mathematics and decathlon”, Track
and Field, vol. 10, pp. 28-30, 1962 (In Russian).

## Kenny et al. (2005)

Title: Determinants of Success in the Olympic Decathlon: Some Statistical Evidence
<br>
Citation: Kenny, I. C., Sprevak, D., Sharp, C., & Boreham, C. (2005). Determinants of success in the olympic decathlon: Some statistical evidence. Journal of Quantitative Analysis in Sports, 1(1), 5.
<br>
<br>
Data: 92 olympic decathletes from 1984 to 2000
<br>
RQ: in an elite subset, are correlations between events still observed?
<br>
<br>
Methods: standardized scores by event. comparison of highest standardized score to average standardized score by athlete
<br>
Findings: 

- Within Van Damme et al's (2002) analysis of 600 decathletes, there is a subset that behaves differently. That is, that a uniform relatively high performance in all individual events is required to effectively compete at the top level.
- Efforts should be made to train for uniformity of performance

## Van Damme et al (2002)

Title: Performance constraints in decathletes
<br>
Citation: Van Damme, R., Wilson, R.S., Vanhooydonck, B. and Aerts, P., Performance
constraints in decathletes, Nature, 2002, 415: 755-756.
<br>
<br>
Data: 600 world class decathletes
<br>
RQ: trade-off between specialist and generalist phenotypes
<br>
<br>
Methods: standardized partial correlation analyses
<br>
Findings: 

- negative correlation between some pairs of events
- "These results seem to support the idea of trade-offs generated by conflicting anatomical (such as relative body weight and limb proportions) and muscle-fibre-type requirements"
- "The influence of an individual athlete’s training schedule or career development on these apparent trade-offs also needs to be determined." (p. 756)
- *This paper is a good starting point for our motivation*

## Ward et al. (2002)

Title: **Find and read this paper**
<br>
Citation: Ward, P., Sprevak, D. and Boreham, C., It takes ten events to make the
Olympic decathlon, International Journal of Mathematical Education in Science &
Technology, 2002, 33:(6) 926-933. 
<br>
<br>
Data: 
<br>
RQ: correlation between events
<br>
<br>
Methods: 
<br>
Findings: 

- 
-

## Linden (1977)

Title: Factor analytical study of olympic decathlon data
<br>
Citation: Linden, M. (1977). Factor analytical study of olympic decathlon data. Research Quarterly. American Alliance for Health, Physical Education and Recreation, 48(3), 562-568.
<br>
<br>
Data: Olympic data from 1948 - 1976, 160 scores from 139 athletes. 
<br>
RQ: correlation between events
<br>
<br>
Methods: PCA
<br>
Findings: 

- four basic events, related to the factors, are sprints, throwing, distance, and jumping. 
- four related skills are running speed, explosive arm strength, running endurance, and explosive
leg strength

## Lee (2010)

Title: A study on the performance patterns of elite decathlon athletes
<br>
Citation: Lee, J. T. (2010). A Study on the performance pattern in the elite decathlon. Journal of the Korean Data and Information Science Society, 21(6), 1071-1079.
<br>
<br>
Data: Top 200 IAAF scores between 1991 and 2009
(*this paper is hard to read, its translation into english is poor. the original paper is in korean*)
<br>
RQ: 
<br>
<br>
Methods: correspondence analysis and canonical correlation analysis
<br>
Findings: 

- "athletes who are strong in track events using speed and who are good at throwing have achieved the highest level" (p. 7)
-

## Tidow (2000)

Title: Challenge decathlon: barriers on the way to becoming the “king of athletes”
<br>
Citation: Tidow, G. (2000). Challenge decathlon: barriers on the way to becoming the “king of athletes”. New Studies in Athletics, 15, 43-52
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: Comparison of decathlete scores to specialist scores
<br>
Findings: 

- efficient and comprehensive simultaneous training for all decathlon events is impossible
- *** Anton needs to read this paper -- a good one linking results to physiology ***

## Jing (2008)

Title: An analysis of the competitive characteristics and strength of the outstanding male decathlon athletes in my country
<br>
Citation: Jing, X. U. 2008. Study on the Competitive Feature and
Actual Strength of Chinese Outstanding Male Decathlon
Athletesl. Journal of Guangzhou Sport University. 28, 5
(December. 2008), 61-64. DOI=
http://dx.doi.org/10.3969/j.issn.1007-323X.2008.05.017
<br>
<br>
Data: Chinese decathletes
(*I cant actually find a copy of this paper. Just the abstract*)
<br>
RQ: 
<br>
<br>
Methods: Gray correlation analysis
<br>
Findings: 

- Chinese decathletes are good at 110mh, PV, 100m, and 400m. I.e., generally have strong scoring ability in the speed events, but are not as good on the other events.
- See similar studies by Huang and He (2013) and Zheng and Jia (2004) using Gray Correlative Analysis
- Huang, C., & He, Y. (2013, August). Grey Correlation Analysis of Decathlon Achievement of the World Elite Athletes Ashton James Eaton. In 2013 International Workshop on Computer Science in Sports (pp. 265-268). Atlantis Press. Accessed via https://www.atlantis-press.com/article/9026.pdf
- ZHENG Yi-le; JIA Chang-zhi. Gray Correlative Analysis of the
Achievement of Top Chinese and Foreign Decathlon Athletes,
Journal of Beijing University of Physical Education,2004,24(8):
1135-1136.


## Dziadek et al. (2018)

Title: Principal component analysis in the study of structure of the best polish decathlon competitors from the period between 1985-2015
<br>
Citation: Dziadek, B., Iskra, J., & Przednowek, K. (2018). Principal Component Analysis in the Study of Structure of the Best Polish Decathlon Competitors from the Period between 1985–2015. Central European Journal of Sport Sciences and Medicine, 23, 77-87.
<br>
<br>
Data: Career data from the top 25 Polish decathletes
<br>
RQ: Patterns occuring between each event and the final results
<br>
<br>
Methods: PCA
<br>
Findings: 

- spring events are correlated with eachother, as are LJ and PV
- "scientific research of decathlon’s structure turned out to be crucial, as it could assist the competitors and trainers in optimising the training process" (p. 78)
- correlation matrices and factors maps -- cool visuals

## Stemmler & Baumler (2005)

Title: **Find this paper**
<br>
Citation: Stemmler, M., Bäumler, G. (2005). The Detection of Types among Decathletes using Configural Frequency Analysis (CFA). Psychology
Science, 47 (3/4), 447–466.
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: PCA
<br>
Findings: 

- physiological charateristics?

## Ertel (2011)

Title: **Find this paper**
<br>
Citation: Ertel, S. (2011). Exploratory factor analysis revealing complex structure. Elsevier, 50 (2),196–200.
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: PCA
<br>
Findings: 

- hidden structure


## Furdal (1986)

Title: **Find this paper**
<br>
Citation: Furdal, S. (1986). Analizy modelowe wyników w dziesięcioboju. Warszawa: Raport Instytutu Sportu
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: PCA
<br>
Findings: 

- 

## Wimmer et al. (2011)

Title: Exploring Competition Performance in Decathlon Using Semi-Parametric Latent Variable Models
<br>
Citation: Wimmer, V., Fenske, N., Pyrka, P., & Fahrmeir, L. (2011). Exploring competition performance in decathlon using semi-parametric latent variable models. Journal of Quantitative Analysis in Sports, 7(4).
<br>
<br>
Data: 3103 results from 1998-2009, age of participants
<br>
RQ: what is the effect of age on latent abilities? 
<br>
<br>
Methods: semi-parametric latent variable models
<br>
Findings: 

- first study of covariate information (i.e., age)
- after adjusting for age, there are four latent factors standing for sprint, jumping, throwing, and endurance abilities
- between age 20 and 35: 
    - throwing abilities increase with age
    - jumping abilities increase some with age
    - spring abilities mostly flat with age until age 30
    - endurance abilities mostly flat with age
- "In comparison to previous analyses, our results confirm the grouping
structure of decathlon disciplines found by Woolf et al. (2007) or Schomaker
and Heumann (2011). Yet, we also used data from non-elite athletes who
achieved less than 7500 total points. Thus, we conclude that the grouping
structure does not seem to depend on the total points but is true for a large
number of athletes." (p. 17)
- **be sure to discuss this study!!**


## Schomaker and Heumann (2011)

Title: Model Averaging in Factor Analysis: An Analysis of Olympic Decathlon Data
<br>
Citation: Schomaker, M. and C. Heumann (2011): “Model averaging in factor analysis:
An analysis of olympic decathlon data,” Journal of Quantitative Analysis in
Sports, 7.
<br>
<br>
Data: 30 athletes from the 2004 olympics
<br>
RQ: what is the dimension of decathlon competitions
<br>
<br>
Methods: likelihood factor analysis
<br>
Findings: 

- athletes with great leg speed who performed well in 100m, 400m, and 110mh. Athletes who perform well in throwing events because of arm strength. Suggest presence of a few latent factors explaining performance. 
- factor 1 is 100 400 100 and negative LJ, 'speed-and-athletic' component
- factor 2 is SP HJ and DT. 'strength-and-technique' component
- factor 3 is 1500m, 'endurance'
- JT and PV don't really fit with any factors, maybe because they are sophisticated. 


## Bilic et al. (2015)

Title: CONTRIBUTION TO DISCIPLINE DECATHLON TOTAL SCORE RESULTS IN RELATION TO DECATHLON AGE AND RESULT-LEVEL 
<br>
Citation: Bilić, M., Smajlovic, N., & Balić, A. (2015). Contribution to discipline decathlon total score results in relation to decathlon age and result-level. Acta Kinesiologica, 9(1), 66-69.
<br>
<br>
Data: junior (n=150) and senior (n=350) data from IAAF 
<br>
RQ: *this paper is a bit hard to read*
<br>
<br>
Methods: regression
<br>
Findings: 

- "junior decatchlon categories show a slightly different structure view of disciplines" than the senior athletes (p. 67)
- scores are a function of natural abilities and also technical preparedness. 

## Next up links

### injuries and training
https://bjsm.bmj.com/content/45/4/346.1.short
https://pubsonline.informs.org/doi/pdf/10.1287/opre.1080.0616?casa_token=SEskYThqpdkAAAAA%3AwLtb2WIhnfYfc6yNXMn7ff4-XlYBDPYf3hyB_j2SGghnGu2H8gqw3zGh_MLNZhxQqgX840M-&
https://www.sciencedirect.com/science/article/abs/pii/S0765159710001607
https://www.sciencedirect.com/science/article/abs/pii/S1350449515300815?casa_token=JqoSpELGxQcAAAAA:ZCUpdhR47OrCPGazdsEtrUVr4oxHTG9Sz2XccDKQeEHkjHqBrgdllu1mtiobZTrtt_jsywAr
https://www.sciencedirect.com/science/article/abs/pii/S0765159712000615


### scoring systems

- Barrow, J. (2014). Decathlon: The Art of Scoring Points. 50 Visions of Mathematics, 11-15.

# Heptathlon

## Dawkins et al. (1999)

Title: **Find and Read this Paper**
<br>
Citation: Dawkins, B. P., Andrea, P. M. and O’Connor, P. M. (1994) Analysis of Olympic heptathlon data. J. Am. Statist. Ass., 89, 1100–1106
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: 
<br>
Findings: 

-
-

## Next up Links
- https://www.mdpi.com/2075-4663/4/1/12/pdf
- https://journals.ekb.eg/article_70742_4ef26bf9ef9ffca53fbb2d1027b8c8ac.pdf
- https://www.researchgate.net/profile/Michael-Froehlich-4/publication/279976560_Zur_Strukturanalyse_des_Mehrkampfs_in_der_Leichtathletik_Eine_empirische_Studie_zum_Zusammenhang_von_Leistung_und_Erfolg_im_Siebenkampf_der_Frauen_und_Zehnkampf_der_Manner/links/55a7c7f108ae5aa1579d83ff/Zur-Strukturanalyse-des-Mehrkampfs-in-der-Leichtathletik-Eine-empirische-Studie-zum-Zusammenhang-von-Leistung-und-Erfolg-im-Siebenkampf-der-Frauen-und-Zehnkampf-der-Maenner.pdf#page=10
- https://elibrary.ru/item.asp?id=40804956
- https://content.iospress.com/articles/journal-of-sports-analytics/jsa200351
- http://www.pf.jcu.cz/stru/katedry/tv/studia_kinantropologica/documents/magazine/SK_vol_21_2020_2.pdf#page=27
- https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1060.9471&rep=rep1&type=pdf
- http://centrostudilombardia.com/wp-content/uploads/IAAF-Prove-Multiple/2003-Training-women-for-the-Heptathlon.pdf

# Pentathlon

## Template

Title: 
<br>
Citation:
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: 
<br>
Findings: 

-
-

## Next up Links
- https://elib.gsu.by/bitstream/123456789/13375/3/%D0%A1%D0%B5%D0%B2%D0%B4%D0%B0%D0%BB%D0%B5%D0%B2_%D0%92%D1%80%D1%83%D0%B1%D0%BB%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9_%D0%9A%D0%BE%D0%B6%D0%B5%D0%B4%D1%83%D0%B1_9%2828%29_2020.pdf
- https://www.mdpi.com/2075-4418/10/10/833/pdf
- https://www.tandfonline.com/doi/pdf/10.1080/02640414.2010.497816?casa_token=m0c2Xq4wOwkAAAAA:a93O7ePJFbvRZf_5moo1-L8bMTYsG11YM1JuzvUHOGbYX8GyguhDNbSBxqffLxCDvtlV4thSdVg
- https://www.tandfonline.com/doi/pdf/10.1080/02640419408732186?casa_token=Kn-DFg8-Gx8AAAAA:taiQ5X_f4bEYCGXpUCMjTh4u7fra2p3Gd6lQcb2ZAo1XscROa23PX5BnBGG9s7JNvOb26RYPOxg
- http://www.sportmont.ucg.ac.me/clanci/SM_October_2020_Ledynakl.pdf
- http://web.b.ebscohost.com/ehost/pdfviewer/pdfviewer?vid=0&sid=ca243312-0d4f-448e-9fb0-1899b851bdb2%40sessionmgr102


# Physio and training

## Template

Title: 
<br>
Citation:
<br>
<br>
Data: 
<br>
RQ: 
<br>
<br>
Methods: 
<br>
Findings: 

-
-

## Next up Links
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6682536/