---
title: "A Latent Profile Growth Analysis of Combined Track and Field Athletes"
author: Anton Hesse and V.N. Vimal Rao
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

At the 2017 World Championships in Athletics, Nafissatou Thiam of Belgium won the women's heptathlon in part by scoring the highest point total in the High Jump, Long Jump, and Shot Put events, and the second highest point total in the Javelin Throw. Two years later at the 2019 World Championships, Katarina Johnson-Thompson of Great Britain and Northern Ireland won the competition by scoring the highest point total in the 200 meters, 800 meters, Long Jump, and High Jump events -- Thiam finished in second. Both of these champion athletes achieved their victories by strong performances in different combinations of events. This is not a reflection of the varying effectiveness of strategies -- both of their personal best point totals are near 7000 points. Instead, Thiam and Johnson-Thompson appear to typify different phenotypes of world-caliber heptathletes, 'jumper-thrower' and 'jumper-runner' respectively. 

Many scholars have examined the performances of multi-event athletes, particularly in the decathlon and heptathlon. These have included correlational analyses to investigate how scores in each constituent event are related (e.g., Majchrzak et al., 2010), 
cluster analyses to identify groups of events in the competitions for which scores are strongly correlated (e.g., Cox and Dunn, 2002), and latent factor analyses to identify patterns in physiological characteristics of top athletes (e.g., Bilic, 2015; Heazlewood et al., 2014; Linden, 1977). As simultaneous specialization in all constituent events is impractical if not impossible (Tidow, 2000; Van Damme et al., 2002), some scholars have interpreted patterns in the relationships between event scores of top athletes in terms of the training regimens that may produce world class multi-event athletes (e.g., Kenny et al., 2005). Some scholars have interpreted results from factor analytic methods such as principal components analysis as patterns in terms of athlete phenotypes, such as 'runner-thrower' or 'thrower-jumper' (e.g., Pavlović & Idrizović, 2017). 

However, to date no longitudinal analysis of multi-event athletes' performances has been conducted, nor has an analysis of the performance of an athlete relative to their phenotype been performed. In order to better understand the patterns in physiological traits of world class multi-event athletes, and to understand their development, this paper describes a latent profile growth analysis on multi-event athletes' at both the collegiate level and the international level. 

# Background

## What are the events? 

## The physiological demands (Anton)

## Analyses People have done, and Gaps in the research.

- people have long analyzed patterns in the performance of events. 
    - clustering, factor analysis, correlation analysis, pca
    - most models indicate 1500m is its own thing, SP JT DT are related, and the spring events are related (with some separating the PV HJ and LJ from the 100m 400m and 110mh)
    - some have interpreted this in terms of the characteristics of athletes, i.e. profiles, and some have interpreted this in terms of the physiological characteristics, i.e., latent traits.
    
- Wimmer et al 2011 considered the effect of age and month of the meet as covariates on the latent factors. the latent factors were interpreted in terms of the physiological skills. athletes' factor scores changed with age. 

- no multivariate analysis of how latent factor scores co-vary across time, or how different profiles' latent scores grow differently over time. furthermore, Wimmer et al included few athletes below the age of 20. therefore, for these important developmental years, we do not know how athletes grow, or if its possible to identify those with the potential to become world champion athletes. 

### RQ

- How do athletes' multi-event scores change over time, and differences exist within or between those with different physiological profiles?
- What patterns in athletes' multi-event scores are detectable between collegiate athletes? 

# Methods

- we're assuming classes/profiles are stable

- during college, you're learning technique, so while classes are static, we might not see that variation. it takes time to develop into the class. 

## Data

## Statistical Method (Corissa)

(1) Classify IAAF best on "peak performance"
(2) Match IAAF peeps to TIFFRS data, analyze growth trajectories
(3) Classify TIFFRS to see how that looks

# Results

## RQ1: Classify IAAF

- graph showing difference in mean profile, and then plot a single person, see how they line up

## RQ2: Growth Trajectory

## RQ3: Classify TIFFRS

# Discussion